### ISSUE TITLE
Eztv seeders/leechers are 'undefined'

### ISSUE THREAD

**Issue by pechitook** [ItzBlitz98/torrentflix#46]
Scraper might be outdated.

**Comment by ItzBlitz98** [comment]
Fixed in https://github.com/ItzBlitz98/torrentflix/commit/3b063d014469145a67fe0a6c0e8559bffca6efba

EZTV never had the ability to show how many leechers and seeders a torrent has, To do this we would have to go to every page the search results returns to grab them and that isn't fair on their servers.
